<center>
<img src="https://laelgelcpublic.s3.sa-east-1.amazonaws.com/lael_50_years_narrow_white.png.no_years.400px_96dpi.png" width="300" alt="LAEL 50 years logo">
<h3>APPLIED LINGUISTICS GRADUATE PROGRAMME (LAEL)</h3>
</center>
<hr>

# Corpus Linguistics - Study 3 - Phase 4 - eyamrog

The aim of this phase is to enrich the `QJPP` corpus with its respective dimension scores obtained via `TagCount`.

## Required Python packages

- pandas
- matplotlib

## Import the required libraries

In [1]:
import pandas as pd
import re
import matplotlib.pyplot as plt

## Define input variables

In [2]:
input_directory = 'cl_st3_ph1_eyamrog'
output_directory = 'cl_st3_ph1_eyamrog'
# EL2AP
counts_el2ap_1 = 'cl_st3_ph1_eyamrog/el2ap/el2ap_1/tagcount/counts_el2ap_1.txt'
counts_el2ap_2 = 'cl_st3_ph1_eyamrog/el2ap/el2ap_2/tagcount/counts_el2ap_2.txt'
counts_el2ap_3 = 'cl_st3_ph1_eyamrog/el2ap/el2ap_3/tagcount/counts_el2ap_3.txt'
counts_el2ap_4 = 'cl_st3_ph1_eyamrog/el2ap/el2ap_4/tagcount/counts_el2ap_4.txt'
counts_el2ap_5 = 'cl_st3_ph1_eyamrog/el2ap/el2ap_5/tagcount/counts_el2ap_5.txt'
counts_el2ap_6 = 'cl_st3_ph1_eyamrog/el2ap/el2ap_6/tagcount/counts_el2ap_6.txt'
counts_el2ap_7 = 'cl_st3_ph1_eyamrog/el2ap/el2ap_7/tagcount/counts_el2ap_7.txt'
# AI-EL2AP
counts_ai_el2ap_1 = 'cl_st3_ph1_eyamrog/ai-el2ap/ai-el2ap_1/tagcount/counts_ai-el2ap_1.txt'
counts_ai_el2ap_2 = 'cl_st3_ph1_eyamrog/ai-el2ap/ai-el2ap_2/tagcount/counts_ai-el2ap_2.txt'
counts_ai_el2ap_3 = 'cl_st3_ph1_eyamrog/ai-el2ap/ai-el2ap_3/tagcount/counts_ai-el2ap_3.txt'
counts_ai_el2ap_4 = 'cl_st3_ph1_eyamrog/ai-el2ap/ai-el2ap_4/tagcount/counts_ai-el2ap_4.txt'
counts_ai_el2ap_5 = 'cl_st3_ph1_eyamrog/ai-el2ap/ai-el2ap_5/tagcount/counts_ai-el2ap_5.txt'
counts_ai_el2ap_6 = 'cl_st3_ph1_eyamrog/ai-el2ap/ai-el2ap_6/tagcount/counts_ai-el2ap_6.txt'
counts_ai_el2ap_7 = 'cl_st3_ph1_eyamrog/ai-el2ap/ai-el2ap_7/tagcount/counts_ai-el2ap_7.txt'

## Extract tagcount summaries from the tagcount files

In [3]:
def tagcount_summary(tagcount_file_path):
    '''
    Extract a summary of the tagcount files
    '''
    data = []

    with open(tagcount_file_path, 'r', encoding='utf-8') as f:
        lines = [line.strip() for line in f if line.strip()]

    i = 0
    while i < len(lines):
        # Parse first line (metadata)
        header = re.split(r'\s+', lines[i])
        filename = header[0]
        type_token = float(header[1])
        word_length = float(header[2])
        word_count = int(header[3])
        i += 1

        # Skip the 10 lines of feature counting
        i += 10

        # Parse final line: 10 values (first 5 = known factor scores, last 5 = unknown)
        tail_values = [float(val) for val in re.split(r'\s+', lines[i])]
        i += 1

        # Store as a dictionary
        entry = {
            'Filename': filename,
            'Type/Token': type_token,
            'Word Length': word_length,
            'Word Count': word_count,
            **{f'Factor {k+1} Score': tail_values[k] for k in range(5)},
            **{f'Unknown {k-4}': tail_values[k] for k in range(5, 10)}
        }
        data.append(entry)

    # Create a DataFrame
    df_tagcount_summary = pd.DataFrame(data)

    return df_tagcount_summary

## Import the data into a DataFrame

In [4]:
df_el2ap_balanced = pd.read_json(f"{input_directory}/df_el2ap_balanced.jsonl", lines=True)

In [5]:
df_el2ap_balanced['Submitted'] = pd.to_datetime(df_el2ap_balanced['Submitted'], unit='ms')
df_el2ap_balanced['Posted'] = pd.to_datetime(df_el2ap_balanced['Posted'], unit='ms')

### Add the `EL2AP Filename` and `AI-EL2AP Filename` columns

In [6]:
df_el2ap_balanced['EL2AP Filename'] = (
    df_el2ap_balanced['Text ID'].astype(str) + '_' +
    df_el2ap_balanced['Section Code'].astype(str) + '_' +
    df_el2ap_balanced['Paragraph Code'].astype(str) + '_el2ap.txt'
)

In [7]:
df_el2ap_balanced['AI-EL2AP Filename'] = (
    df_el2ap_balanced['Text ID'].astype(str) + '_' +
    df_el2ap_balanced['Section Code'].astype(str) + '_' +
    df_el2ap_balanced['Paragraph Code'].astype(str) + '_ai-el2ap.txt'
)

In [8]:
df_el2ap_balanced.shape

(6668, 18)

## Splitting the `df_el2ap_balanced` corpus into `df_el2ap_dimensions` and `df_ai_el2ap_dimensions` corpora

In [9]:
df_el2ap_dimensions = df_el2ap_balanced

In [10]:
df_ai_el2ap_dimensions = df_el2ap_balanced

## Enriching `df_el2ap_dimensions` with factor scores

### Consolidating the tagcount summaries for `EL2AP`

In [11]:
df_tagcount_el2ap_1 = tagcount_summary(counts_el2ap_1)
df_tagcount_el2ap_2 = tagcount_summary(counts_el2ap_2)
df_tagcount_el2ap_3 = tagcount_summary(counts_el2ap_3)
df_tagcount_el2ap_4 = tagcount_summary(counts_el2ap_4)
df_tagcount_el2ap_5 = tagcount_summary(counts_el2ap_5)
df_tagcount_el2ap_6 = tagcount_summary(counts_el2ap_6)
df_tagcount_el2ap_7 = tagcount_summary(counts_el2ap_7)

df_tagcount_el2ap = pd.concat([
    df_tagcount_el2ap_1,
    df_tagcount_el2ap_2,
    df_tagcount_el2ap_3,
    df_tagcount_el2ap_4,
    df_tagcount_el2ap_5,
    df_tagcount_el2ap_6,
    df_tagcount_el2ap_7
], ignore_index=True)

In [12]:
df_tagcount_el2ap.drop(columns=['Unknown 1', 'Unknown 2', 'Unknown 3', 'Unknown 4', 'Unknown 5'], inplace=True)

In [13]:
df_tagcount_el2ap.rename(columns={'Filename': 'EL2AP Filename'}, inplace=True)

In [14]:
df_tagcount_el2ap.shape

(6634, 9)

### Removing texts that have been excluded by `TagCount`

The `TagCount` processing excluded a few texts that have not scored in any of the dimensions. They should removed from the corpus.

In [15]:
tagcount_el2ap_delta = df_el2ap_balanced[
    ~df_el2ap_balanced['EL2AP Filename'].isin(df_tagcount_el2ap['EL2AP Filename'])
]['EL2AP Filename'].tolist()

In [16]:
len(tagcount_el2ap_delta)

34

In [17]:
tagcount_el2ap_delta

['t000004_s7_p9_el2ap.txt',
 't000004_s7_p10_el2ap.txt',
 't000004_s13_p33_el2ap.txt',
 't000009_s16_p18_el2ap.txt',
 't000019_s14_p3_el2ap.txt',
 't000046_s16_p26_el2ap.txt',
 't000049_s14_p9_el2ap.txt',
 't000050_s14_p1_el2ap.txt',
 't000060_s11_p28_el2ap.txt',
 't000073_s21_p30_el2ap.txt',
 't000073_s21_p89_el2ap.txt',
 't000073_s21_p131_el2ap.txt',
 't000073_s21_p133_el2ap.txt',
 't000096_s20_p34_el2ap.txt',
 't000096_s20_p46_el2ap.txt',
 't000096_s20_p82_el2ap.txt',
 't000103_s11_p3_el2ap.txt',
 't000103_s11_p4_el2ap.txt',
 't000103_s11_p13_el2ap.txt',
 't000103_s11_p14_el2ap.txt',
 't000103_s11_p18_el2ap.txt',
 't000103_s14_p6_el2ap.txt',
 't000109_s14_p37_el2ap.txt',
 't000109_s14_p38_el2ap.txt',
 't000109_s14_p39_el2ap.txt',
 't000109_s14_p45_el2ap.txt',
 't000193_s13_p17_el2ap.txt',
 't000274_s10_p22_el2ap.txt',
 't000274_s10_p35_el2ap.txt',
 't000286_s14_p1_el2ap.txt',
 't000286_s19_p10_el2ap.txt',
 't000286_s19_p11_el2ap.txt',
 't000299_s1_p1_el2ap.txt',
 't000305_s14_p9_el2ap.txt']

In [18]:
df_el2ap_dimensions = df_el2ap_dimensions[~df_el2ap_dimensions['EL2AP Filename'].isin(tagcount_el2ap_delta)]

In [19]:
df_el2ap_dimensions.shape

(6634, 18)

### Merging `df_tagcount_el2ap` into `df_el2ap_dimensions` by the `EL2AP Filename` column

In [20]:
df_el2ap_dimensions = df_el2ap_dimensions.merge(df_tagcount_el2ap, on='EL2AP Filename', how='left')

In [21]:
df_el2ap_dimensions

,Title,URL,Authors,Published,PDF Language,PDF URL,Submitted,Posted,Text ID,Discipline,...,EL2AP Filename,AI-EL2AP Filename,Type/Token,Word Length,Word Count,Factor 1 Score,Factor 2 Score,Factor 3 Score,Factor 4 Score,Factor 5 Score
0,"(Fern flora of Viçosa, Minas Gerais State, Bra...",https://preprints.scielo.org/index.php/scielo/...,"Nelson Túlio Lage Pena, Pedro Bond Schwartsburd",Submitted 11/22/2022 - Posted 11/23/2022,PDF,https://preprints.scielo.org/index.php/scielo/...,2022-11-22,2022-11-23,t000000,Biological Sciences,...,t000000_s1_p1_el2ap.txt,t000000_s1_p1_ai-el2ap.txt,26.3,5.8,162,-23.71,-4.13,3.95,-6.61,-3.63
1,"(Fern flora of Viçosa, Minas Gerais State, Bra...",https://preprints.scielo.org/index.php/scielo/...,"Nelson Túlio Lage Pena, Pedro Bond Schwartsburd",Submitted 11/22/2022 - Posted 11/23/2022,PDF,https://preprints.scielo.org/index.php/scielo/...,2022-11-22,2022-11-23,t000000,Biological Sciences,...,t000000_s8_p1_el2ap.txt,t000000_s8_p1_ai-el2ap.txt,20.5,5.4,109,-23.11,-4.52,7.56,-2.94,8.99
2,"(Fern flora of Viçosa, Minas Gerais State, Bra...",https://preprints.scielo.org/index.php/scielo/...,"Nelson Túlio Lage Pena, Pedro Bond Schwartsburd",Submitted 11/22/2022 - Posted 11/23/2022,PDF,https://preprints.scielo.org/index.php/scielo/...,2022-11-22,2022-11-23,t000000,Biological Sciences,...,t000000_s8_p2_el2ap.txt,t000000_s8_p2_ai-el2ap.txt,22.0,5.2,118,-16.08,-5.73,7.47,-6.61,8.36
3,"(Fern flora of Viçosa, Minas Gerais State, Bra...",https://preprints.scielo.org/index.php/scielo/...,"Nelson Túlio Lage Pena, Pedro Bond Schwartsburd",Submitted 11/22/2022 - Posted 11/23/2022,PDF,https://preprints.scielo.org/index.php/scielo/...,2022-11-22,2022-11-23,t000000,Biological Sciences,...,t000000_s8_p3_el2ap.txt,t000000_s8_p3_ai-el2ap.txt,18.3,4.8,97,-2.16,-3.41,-2.12,-1.92,-0.50
4,"(Fern flora of Viçosa, Minas Gerais State, Bra...",https://preprints.scielo.org/index.php/scielo/...,"Nelson Túlio Lage Pena, Pedro Bond Schwartsburd",Submitted 11/22/2022 - Posted 11/23/2022,PDF,https://preprints.scielo.org/index.php/scielo/...,2022-11-22,2022-11-23,t000000,Biological Sciences,...,t000000_s8_p4_el2ap.txt,t000000_s8_p4_ai-el2ap.txt,16.8,5.2,94,-25.59,-5.38,-0.54,-6.61,4.56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6629,Coronavirus 2: Analysis of Regularity of Compl...,https://preprints.scielo.org/index.php/scielo/...,Yuri Morales-López,Submitted 04/10/2020 - Posted 06/04/2020,PDF,https://preprints.scielo.org/index.php/scielo/...,2020-04-10,2020-06-04,t000314,Biological Sciences,...,t000314_s20_p5_el2ap.txt,t000314_s20_p5_ai-el2ap.txt,3.3,4.2,14,-23.82,-5.73,0.97,-6.61,-3.63
6630,Coronavirus 2: Analysis of Regularity of Compl...,https://preprints.scielo.org/index.php/scielo/...,Yuri Morales-López,Submitted 04/10/2020 - Posted 06/04/2020,PDF,https://preprints.scielo.org/index.php/scielo/...,2020-04-10,2020-06-04,t000314,Biological Sciences,...,t000314_s20_p6_el2ap.txt,t000314_s20_p6_ai-el2ap.txt,5.3,4.6,23,-14.05,-5.73,-1.50,-6.61,30.14
6631,Coronavirus 2: Analysis of Regularity of Compl...,https://preprints.scielo.org/index.php/scielo/...,Yuri Morales-López,Submitted 04/10/2020 - Posted 06/04/2020,PDF,https://preprints.scielo.org/index.php/scielo/...,2020-04-10,2020-06-04,t000314,Biological Sciences,...,t000314_s20_p7_el2ap.txt,t000314_s20_p7_ai-el2ap.txt,7.5,5.3,38,-9.58,-4.86,-0.52,-6.61,-3.63
6632,Coronavirus 2: Analysis of Regularity of Compl...,https://preprints.scielo.org/index.php/scielo/...,Yuri Morales-López,Submitted 04/10/2020 - Posted 06/04/2020,PDF,https://preprints.scielo.org/index.php/scielo/...,2020-04-10,2020-06-04,t000314,Biological Sciences,...,t000314_s4_p1_el2ap.txt,t000314_s4_p1_ai-el2ap.txt,10.0,4.9,50,-9.44,-5.07,-0.16,-6.61,11.90
6633,Coronavirus 2: Analysis of Regularity of Compl...,https://preprints.scielo.org/index.php/scielo/...,Yuri Morales-López,Submitted 04/10/2020 - Posted 06/04/2020,PDF,https://preprints.scielo.org/index.php/scielo/...,2020-04-10,2020-06-04,t000314,Biological Sciences,...,t000314_s4_p2_el2ap.txt,t000314_s4_p2_ai-el2ap.txt,5.0,5.6,22,9.06,-2.74,-17.56,-6.61,24.78

In [22]:
df_el2ap_dimensions.isna().sum()

Title                     0
URL                       0
Authors                   0
Published                 0
PDF Language              0
PDF URL                   0
Submitted                 0
Posted                    0
Text ID                   0
Discipline                0
Section                   0
Paragraph                 0
Text Paragraph            0
Text Paragraph ChatGPT    0
Section Code              0
Paragraph Code            0
EL2AP Filename            0
AI-EL2AP Filename         0
Type/Token                0
Word Length               0
Word Count                0
Factor 1 Score            0
Factor 2 Score            0
Factor 3 Score            0
Factor 4 Score            0
Factor 5 Score            0
dtype: int64

#### Exporting to a file

In [23]:
df_el2ap_dimensions.to_json(f"{output_directory}/df_el2ap_dimensions.jsonl", orient='records', lines=True)

In [24]:
df_el2ap_dimensions.to_csv(f"{output_directory}/df_el2ap_dimensions.tsv", sep='\t', index=False, encoding='utf-8', lineterminator='\n')

In [25]:
df_el2ap_dimensions.to_excel(f"{output_directory}/df_el2ap_dimensions.xlsx")

## Enriching `df_ai_el2ap_dimensions` with factor scores

### Consolidating the tagcount summaries for `AI-EL2AP`

In [26]:
df_tagcount_ai_el2ap_1 = tagcount_summary(counts_ai_el2ap_1)
df_tagcount_ai_el2ap_2 = tagcount_summary(counts_ai_el2ap_2)
df_tagcount_ai_el2ap_3 = tagcount_summary(counts_ai_el2ap_3)
df_tagcount_ai_el2ap_4 = tagcount_summary(counts_ai_el2ap_4)
df_tagcount_ai_el2ap_5 = tagcount_summary(counts_ai_el2ap_5)
df_tagcount_ai_el2ap_6 = tagcount_summary(counts_ai_el2ap_6)
df_tagcount_ai_el2ap_7 = tagcount_summary(counts_ai_el2ap_7)

df_tagcount_ai_el2ap = pd.concat([
    df_tagcount_ai_el2ap_1,
    df_tagcount_ai_el2ap_2,
    df_tagcount_ai_el2ap_3,
    df_tagcount_ai_el2ap_4,
    df_tagcount_ai_el2ap_5,
    df_tagcount_ai_el2ap_6,
    df_tagcount_ai_el2ap_7
], ignore_index=True)

In [27]:
df_tagcount_ai_el2ap.drop(columns=['Unknown 1', 'Unknown 2', 'Unknown 3', 'Unknown 4', 'Unknown 5'], inplace=True)

In [28]:
df_tagcount_ai_el2ap.rename(columns={'Filename': 'AI-EL2AP Filename'}, inplace=True)

In [29]:
df_tagcount_ai_el2ap.shape

(6653, 9)

### Removing texts that have been excluded by `TagCount`

The `TagCount` processing excluded a few texts that have not scored in any of the dimensions. They should removed from the corpus.

In [30]:
tagcount_ai_el2ap_delta = df_el2ap_balanced[
    ~df_el2ap_balanced['AI-EL2AP Filename'].isin(df_tagcount_ai_el2ap['AI-EL2AP Filename'])
]['AI-EL2AP Filename'].tolist()

In [31]:
len(tagcount_ai_el2ap_delta)

15

In [32]:
tagcount_ai_el2ap_delta

['t000050_s14_p1_ai-el2ap.txt',
 't000060_s11_p28_ai-el2ap.txt',
 't000073_s21_p57_ai-el2ap.txt',
 't000073_s21_p89_ai-el2ap.txt',
 't000073_s21_p133_ai-el2ap.txt',
 't000096_s20_p46_ai-el2ap.txt',
 't000103_s11_p3_ai-el2ap.txt',
 't000103_s11_p4_ai-el2ap.txt',
 't000103_s11_p13_ai-el2ap.txt',
 't000103_s11_p14_ai-el2ap.txt',
 't000103_s11_p18_ai-el2ap.txt',
 't000109_s14_p38_ai-el2ap.txt',
 't000109_s14_p39_ai-el2ap.txt',
 't000274_s10_p35_ai-el2ap.txt',
 't000286_s14_p1_ai-el2ap.txt']

In [33]:
df_ai_el2ap_dimensions = df_ai_el2ap_dimensions[~df_ai_el2ap_dimensions['AI-EL2AP Filename'].isin(tagcount_ai_el2ap_delta)]

In [34]:
df_ai_el2ap_dimensions.shape

(6653, 18)

### Merging `df_tagcount_ai_el2ap` into `df_ai_el2ap_dimensions` by the `AI-EL2AP Filename` column

In [35]:
df_ai_el2ap_dimensions = df_ai_el2ap_dimensions.merge(df_tagcount_ai_el2ap, on='AI-EL2AP Filename', how='left')

In [36]:
df_ai_el2ap_dimensions

,Title,URL,Authors,Published,PDF Language,PDF URL,Submitted,Posted,Text ID,Discipline,...,EL2AP Filename,AI-EL2AP Filename,Type/Token,Word Length,Word Count,Factor 1 Score,Factor 2 Score,Factor 3 Score,Factor 4 Score,Factor 5 Score
0,"(Fern flora of Viçosa, Minas Gerais State, Bra...",https://preprints.scielo.org/index.php/scielo/...,"Nelson Túlio Lage Pena, Pedro Bond Schwartsburd",Submitted 11/22/2022 - Posted 11/23/2022,PDF,https://preprints.scielo.org/index.php/scielo/...,2022-11-22,2022-11-23,t000000,Biological Sciences,...,t000000_s1_p1_el2ap.txt,t000000_s1_p1_ai-el2ap.txt,29.3,6.0,162,-25.65,-2.95,5.42,-2.14,-0.82
1,"(Fern flora of Viçosa, Minas Gerais State, Bra...",https://preprints.scielo.org/index.php/scielo/...,"Nelson Túlio Lage Pena, Pedro Bond Schwartsburd",Submitted 11/22/2022 - Posted 11/23/2022,PDF,https://preprints.scielo.org/index.php/scielo/...,2022-11-22,2022-11-23,t000000,Biological Sciences,...,t000000_s8_p1_el2ap.txt,t000000_s8_p1_ai-el2ap.txt,20.8,5.7,110,-24.66,-4.53,1.32,-2.97,8.94
2,"(Fern flora of Viçosa, Minas Gerais State, Bra...",https://preprints.scielo.org/index.php/scielo/...,"Nelson Túlio Lage Pena, Pedro Bond Schwartsburd",Submitted 11/22/2022 - Posted 11/23/2022,PDF,https://preprints.scielo.org/index.php/scielo/...,2022-11-22,2022-11-23,t000000,Biological Sciences,...,t000000_s8_p2_el2ap.txt,t000000_s8_p2_ai-el2ap.txt,21.0,5.4,113,-19.91,-5.44,12.07,-6.61,4.52
3,"(Fern flora of Viçosa, Minas Gerais State, Bra...",https://preprints.scielo.org/index.php/scielo/...,"Nelson Túlio Lage Pena, Pedro Bond Schwartsburd",Submitted 11/22/2022 - Posted 11/23/2022,PDF,https://preprints.scielo.org/index.php/scielo/...,2022-11-22,2022-11-23,t000000,Biological Sciences,...,t000000_s8_p3_el2ap.txt,t000000_s8_p3_ai-el2ap.txt,20.3,5.3,102,-4.38,-1.96,5.69,-6.61,6.96
4,"(Fern flora of Viçosa, Minas Gerais State, Bra...",https://preprints.scielo.org/index.php/scielo/...,"Nelson Túlio Lage Pena, Pedro Bond Schwartsburd",Submitted 11/22/2022 - Posted 11/23/2022,PDF,https://preprints.scielo.org/index.php/scielo/...,2022-11-22,2022-11-23,t000000,Biological Sciences,...,t000000_s8_p4_el2ap.txt,t000000_s8_p4_ai-el2ap.txt,17.8,5.3,104,-27.99,-3.88,2.43,-3.50,5.23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6648,Coronavirus 2: Analysis of Regularity of Compl...,https://preprints.scielo.org/index.php/scielo/...,Yuri Morales-López,Submitted 04/10/2020 - Posted 06/04/2020,PDF,https://preprints.scielo.org/index.php/scielo/...,2020-04-10,2020-06-04,t000314,Biological Sciences,...,t000314_s20_p5_el2ap.txt,t000314_s20_p5_ai-el2ap.txt,4.8,5.3,21,-32.59,-5.73,0.97,-6.61,11.73
6649,Coronavirus 2: Analysis of Regularity of Compl...,https://preprints.scielo.org/index.php/scielo/...,Yuri Morales-López,Submitted 04/10/2020 - Posted 06/04/2020,PDF,https://preprints.scielo.org/index.php/scielo/...,2020-04-10,2020-06-04,t000314,Biological Sciences,...,t000314_s20_p6_el2ap.txt,t000314_s20_p6_ai-el2ap.txt,5.8,5.5,25,-10.62,1.68,-10.79,-6.61,2.43
6650,Coronavirus 2: Analysis of Regularity of Compl...,https://preprints.scielo.org/index.php/scielo/...,Yuri Morales-López,Submitted 04/10/2020 - Posted 06/04/2020,PDF,https://preprints.scielo.org/index.php/scielo/...,2020-04-10,2020-06-04,t000314,Biological Sciences,...,t000314_s20_p7_el2ap.txt,t000314_s20_p7_ai-el2ap.txt,9.8,5.8,44,-31.35,-3.97,6.37,-6.61,-0.18
6651,Coronavirus 2: Analysis of Regularity of Compl...,https://preprints.scielo.org/index.php/scielo/...,Yuri Morales-López,Submitted 04/10/2020 - Posted 06/04/2020,PDF,https://preprints.scielo.org/index.php/scielo/...,2020-04-10,2020-06-04,t000314,Biological Sciences,...,t000314_s4_p1_el2ap.txt,t000314_s4_p1_ai-el2ap.txt,10.8,5.8,51,-16.02,-2.92,-6.86,-6.61,23.85
6652,Coronavirus 2: Analysis of Regularity of Compl...,https://preprints.scielo.org/index.php/scielo/...,Yuri Morales-López,Submitted 04/10/2020 - Posted 06/04/2020,PDF,https://preprints.scielo.org/index.php/scielo/...,2020-04-10,2020-06-04,t000314,Biological Sciences,...,t000314_s4_p2_el2ap.txt,t000314_s4_p2_ai-el2ap.txt,6.0,6.0,25,-9.55,-4.41,0.97,6.30,-3.63

In [37]:
df_ai_el2ap_dimensions.isna().sum()

Title                     0
URL                       0
Authors                   0
Published                 0
PDF Language              0
PDF URL                   0
Submitted                 0
Posted                    0
Text ID                   0
Discipline                0
Section                   0
Paragraph                 0
Text Paragraph            0
Text Paragraph ChatGPT    0
Section Code              0
Paragraph Code            0
EL2AP Filename            0
AI-EL2AP Filename         0
Type/Token                0
Word Length               0
Word Count                0
Factor 1 Score            0
Factor 2 Score            0
Factor 3 Score            0
Factor 4 Score            0
Factor 5 Score            0
dtype: int64

#### Exporting to a file

In [38]:
df_ai_el2ap_dimensions.to_json(f"{output_directory}/df_ai_el2ap_dimensions.jsonl", orient='records', lines=True)

In [39]:
df_ai_el2ap_dimensions.to_csv(f"{output_directory}/df_ai_el2ap_dimensions.tsv", sep='\t', index=False, encoding='utf-8', lineterminator='\n')

In [40]:
df_ai_el2ap_dimensions.to_excel(f"{output_directory}/df_ai_el2ap_dimensions.xlsx")